### ISSUE TITLE
Package format issue?

### ISSUE THREAD

**Issue by rmrt1n** [carbon-design-system/carbon-icons-svelte#129]
Hi, I'm using the icons package in a sveltekit project, and when I run the dev server with `npm run dev`, this is the output:
`carbon-icons-svelte doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`.
Everything works fine though.

**Comment by metonym** [comment]
What version are you using?

This should be fixed in [v10.44.3](https://github.com/carbon-design-system/carbon-icons-svelte/releases/tag/v10.44.3).

**Comment by rmrt1n** [comment]
ah I'm using v10.44.2. The message went away after upgrading. thanks
