### ISSUE TITLE
Passing v11 icons to components as prop with specific size

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-icons-svelte#140]
Just saw the release notes and was wondering how one is then supposed to pass icons of a specific size to e.g. the Carbon components that take the icon component itself as a prop, e.g.

```svelte
<Button icon={Add} />
```

**Comment by metonym** [comment]
Are you referring the `Button` specifically? It only allows the `16` size.

Try passing `Add24` through. It will look the same as `Add16`:

```svelte
<script>
  import { Button } from "carbon-components-svelte";
  import Add24 from "carbon-icons-svelte/lib/Add24";
</script>

<Button iconDescription="Tooltip text" icon={Add24} />
```

**Comment by brunnerh** [comment]
Oh, interesting, never noticed that.

I guess this is not an issue then, if this holds in general and the icons do not really differ other than in scale (e.g. small adjustments for better pixel alignments in the various sizes are conceivable).

**Comment by metonym** [comment]
In cases where icon sizes do matter, many components provide an `icon` slot to allow the declarative approach.

```svelte
<Add slot="icon" size={20} />
```

Worst case is to wrap the component and pass it as a prop.

```svelte
<!-- Add20.svelte -->
<Add size={20} />
```

**Comment by amcelroy** [comment]
Sorry to resurrect a closed issue, but I have a similar issue. I am using the Carbon Components Svelte library and would like to pass in larger icons, specifically for the  `UIShell` component. After using `npm` to install the Carbon Icons, there aren't any pre-defined icons of a certain size. For example, I can import `Catalog` but there is no `Catalog32` and noted in some of the examples. 

Is there an additional build step?

**Comment by metonym** [comment]
@amcelroy 

To pass custom-size icons as props, the workaround is to create a separate component that utilizes the `size` prop, and pass the wrapped component through the `icon` prop.

```svelte
<!-- CustomIcon.svelte -->

<script>
  import AccumulationIce from "carbon-icons-svelte/lib/AccumulationIce.svelte";
</script>

<AccumulationIce size={32} />
```

```svelte
<script>
  import { Component } from "library";
  import CustomIcon from "./CustomIcon.svelte";
</script>

<Component icon={CustomIcon} />
```

**Comment by amcelroy** [comment]
Thank you, this is a great example!
