### ISSUE TITLE
Mention breaking changes of upstream library in release notes?

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon-icons-svelte#143]
v11 comes with the breaking changes of `@carbon/icons`, I specifically noticed that the `Delete` icon was gone and found out that `TrashCan` is what should be used (descriptive over semantic 👍).

Apparently `Delete` [along with several other other icons](https://github.com/carbon-design-system/carbon/pull/11062/commits/c79d2f73dceac9922e45b51c68c69fb60bcb6166#diff-1bed7d38a8bb842adf21440387c14428c3bc4671099fe255be8e15a80dfd04f3) has been removed as it had been previously deprecated.

Not sure why this is marked as "feature" in the [release notes](https://github.com/carbon-design-system/carbon/releases/tag/v11.0.1) 😅

> New features 🚀
> - feat(project): update elements packages to v11 layout (https://github.com/carbon-design-system/carbon/pull/11078) ([9ed74042d](https://github.com/carbon-design-system/carbon/commit/9ed74042d))
> - feat(icons): remove deprecated icons (https://github.com/carbon-design-system/carbon/pull/11062) ([eda5c7de6](https://github.com/carbon-design-system/carbon/commit/eda5c7de6))

Also, the lack of a closing `}` here bugs me:
![image](https://user-images.githubusercontent.com/834235/161640817-939c5f0e-6652-4d74-9f44-4e61041b7842.png)

**Comment by Addeuz** [comment]
Also, forwarded events `on:click` etc has also been removed. So now I have do wrap the icons in a div if I want to be able to click on them? Seems like a bad choice

**Comment by brunnerh** [comment]
@Addeuz That should not be done anyway because of accessibility. If something should be clickable, it should be wrapped in a button or link.

**Comment by Addeuz** [comment]
We use icons as buttons when a button is to small. And using a link for a click that isn't navigation is also bad a11y.

![image](https://user-images.githubusercontent.com/12641358/163327208-2a31a740-0b38-46ba-9317-39bd091c9ccd.png)

We also add a `tabindex` to the icon so it can be tapped through. Idk if we can make it any more compliant with a11y. But if someone have tips they are much appreciated.

But now without the `on:click` we have to put a div around the icons and put the `on:click` and  `tabindex` on the div

**Comment by brunnerh** [comment]
`tabindex` is almost useless, if you do not additionally handle key events, the click handler will not fire on pressing enter/space if the element is not a link/button. Obviously links should only be used for navigation. In addition to being triggered on enter/space the element should also be given `role=button`.

All of this is wasted effort, you can just use a regular `button`, as intended. "when a button is too small" is thinking about a button as fixed visual concept, all you have to do is style it accordingly. Usually I just add a CSS class that removes all default styling for this purpose, it is way easier than trying to create all the interactivity and accessibility features from scratch.

```css
.bare-button {
  background: none;
  border: none;
  margin: 0;
  padding: 0;
  font-family: inherit;
  font-size: inherit;
}
```

(This might need additional properties, depending on what other styles you have applied.)

**Comment by Addeuz** [comment]
My edit was to late, but yes that is what I noticed. The enter key did not register as a click. And we used
```css
button {
  all: unset;
}
```

to remove all the styles....

**Comment by metonym** [comment]
I will commit to communicating breaking changes more explicitly.
