### ISSUE TITLE
SquareSolid icon builds as undefined

### ISSUE THREAD

**Issue by tmarsik42** [carbon-design-system/carbon-icons-svelte#191]
https://carbon-icons-svelte.onrender.com/

<img width="604" alt="Snímek obrazovky 2024-09-30 v 16 00 04" src="https://github.com/user-attachments/assets/ab94ed29-5fa9-41a5-96f7-9d000db49cde">

**Comment by metonym** [comment]
Thank you for reporting.

Fixed in [v12.11.1](https://github.com/carbon-design-system/carbon-icons-svelte/releases/tag/v12.11.1)
